# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Build Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Start xcode build 🛠
      run: |
        xcodebuild build -project HiStock/HiStock.xcodeproj -scheme HiStock -destination 'platform=iOS Simulator,name=iPhone 15'
    - name: Run Test
      run: | 
        xcodebuild clean test -project HiStock/HiStock.xcodeproj -scheme HiStock -destination "platform=iOS Simulator,name=iPhone 15"
